apiVersion : apps/v1
kind: Deployment  
metadata:
  name: consumer-deployment 
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: himateja0206/consumer:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "password"
            - name: RABBITMQ_URL
              value: "amqp://user:password@rabbitmq.messaging.svc.cluster.local:5672"
            - name: QUEUE_NAME
              value: "task_queue"



